application: dice-rolls
runtime: python27
version: 1
api_version: 1
threadsafe: false

handlers:
- url: /img
  static_dir: img

- url: /.*
  script: dice.app

libraries:
- name: webapp2
  version: latest
